
int bitXor(int, int);
int test_bitXor(int, int);
int allEvenBits();
int test_allEvenBits();
int logicalShift(int, int);
int test_logicalShift(int, int);
int absVal(int);
int test_absVal(int);
int bang(int);
int test_bang(int);
int tmax();
int test_tmax();
int fitsBits(int, int);
int test_fitsBits(int, int);
int divpwr2(int, int);
int test_divpwr2(int, int);
int negate(int);
int test_negate(int);
int isPositive(int);
int test_isPositive(int);
int isLessOrEqual(int, int);
int test_isLessOrEqual(int, int);
int isNonZero(int);
int test_isNonZero(int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
int float_f2i(unsigned);
int test_float_f2i(unsigned);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
